- name: Create 'resolved.conf.d' directory
  file:
    path: '/etc/systemd/resolved.conf.d'
    state: directory
    mode: "0755"
  when: bind_disable_dnsstublistener or bind_override_systemd_resolved

- name: Disable the systemd-resolved controlled DNSStubListener
  include_tasks: disable_dnsstublistener.yml
  when: bind_disable_dnsstublistener

- name: "Create expected folders"
  file:
    state: directory
    path: "{{ item }}"
    mode: '0775'
    owner: 'root'
    group: '101'
  loop:
    - "{{ bind_container_base_dir }}"
    - "{{ bind_container_base_dir }}/config"
    - "{{ bind_container_base_dir }}/zones"
    - "{{ bind_container_base_dir }}/logs"

- name: Copy rndc keys
  template:
    src: "bind/rndc.key.j2"
    dest: "{{ bind_container_base_dir }}/config/{{ name }}.key"
    mode: '0440'
    owner: 'root'
    group: '101'
  vars:
    name: "{{ item.key }}"
    control: "{{ item.value }}"
  loop: "{{ bind_controls | dict2items }}"
  notify:
    - "Reload Bind"

- name: Copy Bind configuration files
  template:
    src: "bind/{{ item }}"
    dest: "{{ bind_container_base_dir }}/config/{{ item | regex_replace('.j2', '') }}"
    mode: '0664'
    owner: 'root'
    group: '101'
  loop:
    - "named.conf.local.j2"
    - "named.conf.options.j2"
    - "named.conf.logging.j2"
  notify:
    - "Reload Bind"

- name: Update primary zones
  include_tasks: update_zone.yml
  vars:
    domain: "{{ outer_item.key }}"
    zone: "{{ outer_item.value }}"
  loop: "{{ bind_zones | dict2items }}"
  loop_control:
    loop_var: "outer_item"
  when: zone.type in [ "master", "primary" ]

- name: Start Bind container
  docker_container:
    name: "{{ bind_container_name }}"
    image: "{{ bind_container_image }}"
    pull: yes
    state: started
    restart_policy: unless-stopped
    command: "{{ bind_container_command }}"
    volumes:
      - "{{ bind_container_base_dir }}/config:/etc/bind/local-config:ro"
      - "{{ bind_container_base_dir }}/zones:/var/cache/bind"
      - "{{ bind_container_base_dir }}/logs:/var/log/bind"
      - "{{ bind_container_base_dir }}/entrypoint.d:/entrypoint.d"
    comparisons:
      networks: strict
    network_mode: "{{ bind_use_host_network | bool | ternary('host', omit) }}"
    networks: "{{ bind_use_host_network | bool | ternary(omit, bind_container_networks) }}"
    published_ports: "{{ bind_use_host_network | bool | ternary(omit, bind_container_ports) }}"
    env:
      BIND_LOG: "{{ bind_log_force_stderr | ternary('-g', '-f') }}"

- name: Override nameservers set by Openresolv
  import_tasks: override_openresolv.yml
  when: bind_override_openresolv

- name: Override nameservers set by systemd-resolved
  import_tasks: override_systemd_resolved.yml
  when: bind_override_systemd_resolved
