- name: Configure systemd-resolved to use our desired nameservers
  template:
    src: 'resolved.conf.d/override_dns.conf.j2'
    dest: '/etc/systemd/resolved.conf.d/override_dns.conf'
    mode: "0644"
  notify: Reload systemd resolved
