- name: Reload systemd resolved
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: '{{ item }}'
  with_items:
    - systemd-resolved
    - systemd-networkd

- name: "Reload Bind"
  command: "docker kill --signal=HUP {{ bind_container_name }}"
